
# **1. Basic Array Manipulation:**


Create a 1D array with values ranging from 0 to 9.


In [1]:
import numpy as np
array = np.arange(10)

In [2]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Reshape the array into a 3x3 matrix.

Explore Reshape Function

In [18]:
num_1d = np.array([1,2,3,4,5,6,7,8,9])
num_1d.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Access the element at the second row, second column.


In [41]:
num_1d[4]

5

Perform element-wise addition, subtraction, multiplication, and division on two arrays [1, 2, 3] and [4, 5, 6].


In [19]:
array1=np.array([1,2,3])
array2=np.array([4,5,6])

array1+array2

array1-array2

array1*array2

array1/array2

array([0.25, 0.4 , 0.5 ])

Find the sum, mean, and standard deviation of the array [1, 2, 3, 4, 5].


In [24]:
array = np.array([1,2,3,4,5])
print(array.mean())
print(array.std())
print(array.sum())



3.0
1.4142135623730951
15


Reshape the array [1, 2, 3, 4, 5, 6] into a 2x3 array.

Explore Reshape

In [22]:
num_1d=np.array([1,2,3,4,5,6])
num_1d.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])


# **2. Indexing and Slicing:**


Create a 5x5 array with random integers.


In [26]:
random_num = np.random.randint(0,100,size=(5,5))
print(random_num)

[[10 14 68 60  6]
 [66 28 22 73 15]
 [61  6 83  0 52]
 [66 46 76 31 66]
 [72 31 25  6 75]]


Replace all values in the sub-array with a specific value.


In [27]:
random_num[:,:]=10   
random_num

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

Extract the subarray [[3, 4], [7, 8]] from the array [[1, 2], [3, 4], [5, 6], [7, 8]].


In [37]:
arr=np.array([[1,2] , [3,4] , [5,6] , [7,8]])
arr
arr[[1,3]]

array([[3, 4],
       [7, 8]])

# **3. Broadcasting:**

Create a 2D array of shape (3, 3) with values from 0 to 2.


In [49]:
array = np.array([0,1,2])
array
# title
new_array=np.tile(array,(3,1))
new_array

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [ ]:
import numpy as np
array_2d=np.random.randiant(0,100,size(3,3))
array_1d=np.random.randiant(0,100,size(3,1))
print("2d Array:")
print(array_2d)
print("\n1d array:")
print(array_1d)
result=array_2d+array1d


# **4. Concatenation and Splitting**


1.   Create two 2D arrays of shape (3, 3) with random integers.
2.   Concatenate them horizontally and vertically.
3.   Split the concatenated arrays back into the original arrays.


In [52]:
random_array1=np.random.randint(1,100,size=(3,3))
random_array1



array([[55, 39, 25],
       [20, 40, 65],
       [57, 49, 94]])

In [53]:
random_array2=np.random.randint(1,100,size=(3,3))
random_array2

array([[28, 77, 82],
       [83, 49, 26],
       [56, 11, 85]])

In [54]:
concatenated_horizontally=np.hstack((random_array1,random_array2))
concatenated_horizontally

array([[55, 39, 25, 28, 77, 82],
       [20, 40, 65, 83, 49, 26],
       [57, 49, 94, 56, 11, 85]])

In [55]:
concatenated_vertically=np.vstack((random_array1,random_array2))
concatenated_vertically

array([[55, 39, 25],
       [20, 40, 65],
       [57, 49, 94],
       [28, 77, 82],
       [83, 49, 26],
       [56, 11, 85]])

In [58]:
splitted_array =np.hsplit(concatenated_horizontally,2)
splitted_array[1]

array([[28, 77, 82],
       [83, 49, 26],
       [56, 11, 85]])

In [59]:
splitted_array =np.hsplit(concatenated_vertically,2)
splitted_array[1]

array([[28, 77, 82],
       [83, 49, 26],
       [56, 11, 85]])

# **Bonus Question**

Find mode of this array  = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]

Hint: Use count and also loop

In [70]:
import numpy as np
array=[1,2,1,2,3,4,5,6,8,9,1,2,2,2,2,2,1,1,1,1,1,2,5]
count_dict={}               
for i  in array:
    if i in count_dict:
      count_dict[i]+=1
    else: 
        count_dict[i]=1
count_dict       

{1: 8, 2: 8, 3: 1, 4: 1, 5: 2, 6: 1, 8: 1, 9: 1}

In [72]:
mode=none
max_count=0
for key values in count_dict.items ():
    if va;ue > max_count:
      mode=key
print(mode,max_count)


SyntaxError: invalid syntax (3307981334.py, line 3)

# **Notes**


1.   All the Questions carry Equal Points (2 points)

2.   Bonus Question carry 5 points

3.   Review lecture for any query

Good Luck!

